### ISSUE TITLE
[Bug]: Cant craft anything from the mod (1.16.5)

### ISSUE THREAD

**Issue by Chrossta** [LordDeatHunter/FabricWaystones#241] opened 2023-12-22 21:58 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

I just cant i tried changeing the version of the mod and everything recipes dont appear in NEI or when i try to craft them by hand and its the base version of the mod i didnt mess with the config in anyway shape or form, and in curse forge it says its the latest version

### To Reproduce

just download the mod

### Expected behavior

to be able to craft liek it says everywhere

### Mod Version

v2.0.2

### Minecraft Version

1.16.5

### Java Version

Java 18+

### Fabric Version

- **Fabric:** ex. 0.12.5-1-17-1
- **Fabric API:** ex. 0.42.1+1.17

**Comment by LordDeatHunter** [comment] 2023-12-23 20:28
Do you have Charm installed? I think that was causing issues in the older versions.

**Comment by LordDeatHunter** [comment] 2023-12-23 20:30
Duplicate of #215

**Closed** 2023-12-23 20:30 UTC
Labels: bug
