### ISSUE TITLE
[Bug]: Game crashes when placing waystone taken from village

### ISSUE THREAD

**Issue by FleshEatingBeans** [LordDeatHunter/FabricWaystones#198] opened 2023-05-08 19:44 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Description

A player on my server (4 people online at once maximum) took a waystone from a village and attempted to place it in their house. This action reliably crashes the game, waystone remains in active hand and is not placed upon reload. The server remains up. 

### To Reproduce

1. Collect waystone from village
2. Attempt to place it within your house
3. Other player placing waystone does not cause a crash, further interaction with waystone normal

### Expected behavior

No crash

### Mod Version

v3.0.7 or newer

### Minecraft Version

1.19.3 or newer

### Java Version

Java 18

### Fabric Version

- **Fabric:** ex. 0.12.5-1-17-1
- **Fabric API:** ex. 0.42.1+1.17

### Relevant log output

```shell
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to up on Block{fwaystones:waystone}, it is not an allowed value
```

**Comment by LordDeatHunter** [comment] 2023-05-08 19:48
Duplicate of #196, already fixed in 3.0.8.

**Closed** 2023-10-13 16:20 UTC
Labels: bug
