### ISSUE TITLE
[Bug]: 1.19 Cant teleport between waystones

### ISSUE THREAD

**Issue by pewblaze** [LordDeatHunter/FabricWaystones#134] opened 2022-07-09 11:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I cant teleport between waystones. The log doesnt say anything for me, maybe you can track something down? Or are there any known incomp. with other mods? Ive got a lot of mods, so i assume that one is causing this ^^" 

### To Reproduce

Build 2 Waystones
Try to teleport 
Doesnt work

### Expected behavior

Build 2 Waystones
Try to teleport 
Teleport

### Mod Version

v2.5.0

### Minecraft Version

1.19

### Java Version

Java 18

### Fabric Version

Fabric Modloader 0.14.8
fabric-api-0.57.0+1.19

Mod Version:
wraith-waystones-3.0.2+mc1.19

### Anything else?

[latest.log](https://github.com/LordDeatHunter/FabricWaystones/files/9076425/latest.log)

**Comment by LordDeatHunter** [comment] 2022-07-09 11:53
Is there anything showing up on the action bar (above the inventory hotbar) when trying to teleport? Since 3.0.2 I made it so that the action bar shows the reason why you cannot teleport (eg. not enough xp, not enough health, etc.)

**Comment by LordDeatHunter** [comment] 2022-07-09 11:56
Sending the configs would also help :)

**Comment by pewblaze** [comment] 2022-07-09 12:20
I tried again and nothing happens. Theres also nothing showing up. 
I did change the config to an item from a mod, but also tried it with ender pearls. Didnt work.
I deleted the config to try it with the new generated one. Also didnt work

[latest.log](https://github.com/LordDeatHunter/FabricWaystones/files/9076477/latest.log)

Cant load up .json so i changed it to a .txt file:
[config.txt](https://github.com/LordDeatHunter/FabricWaystones/files/9076481/config.txt)

**Comment by LordDeatHunter** [comment] 2022-07-09 12:25
Hmm, it could be some sort of mod incompatibility. Can you export and send me the pack?

**Comment by pewblaze** [comment] 2022-07-09 12:31
Yeah i thought. Not sure which mod could cause this. 
There you go: 
https://easyupload.io/bya8m3

**Comment by LordDeatHunter** [comment] 2022-07-17 09:27
I tried last week, and had another try earlier today on a fresh download, but I'm unable to get the pack to start, it doesn't progress past the loading screen. The logs don't update after a certain time has passed either.

**Comment by ishland** [comment] 2022-07-18 02:04
I can't reproduce this with VMP on FabricWaystones development environment. Clicking these labels on waystones UI just teleports immediately.

**Comment by pewblaze** [comment] 2022-07-20 22:06
The loading takes a lil bit of time (big pack + resource packs). You could delete the resource packs in config/openloader. The pack is a wip. Not sure why it didnt work with the mod and works without for me. But i didnt try it again.

**Comment by LordDeatHunter** [comment] 2022-07-21 18:32
Should I close this issue then?

**Comment by pewblaze** [comment] 2022-07-27 08:18
Sure :)

**Closed** 2022-07-27 09:43 UTC
Labels: bug, compat issue
