### ISSUE TITLE
[Bug]: i tried teleporting my dogs with leads all of them teleported except one 

### ISSUE THREAD

**Issue by popojill** [LordDeatHunter/FabricWaystones#148] opened 2022-09-11 09:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

please help telling me if there is any other way to teleport, do they need to sit and have a lead on with teleporting? do i need certain ex levels to teleport them too?

### To Reproduce

please help lmao

### Expected behavior

nil

### Mod Version

v2.5.0

### Minecraft Version

1.19

### Java Version

Java 18

### Fabric Version

- **Fabric:** ex. 0.12.5-1-17-1
- **Fabric API:** ex. 0.42.1+1.17

### Relevant log output

```shell
non
```

### Anything else?

non

**Comment by LordDeatHunter** [comment] 2022-09-11 11:33
Teleporting other entities with you is kind of broken even in vanilla Minecraft (either via `/tp` or via nether/end portals).
Not much I can do here. Either I or FabricAPI would need to create some sort of custom fix, and I'm not sure when something like that would happen, as I don't have a lot of free time these days, and I don't know if it's something the Fabric team wants in their API.

**Comment by LordDeatHunter** [comment] 2023-03-05 20:53
Closing as duplicate of #168

**Closed by LordDeatHunter** 2023-03-05 20:53 UTC
Labels: bug
