### ISSUE TITLE
[Feature]: Teleportation on\w Mounts

### ISSUE THREAD

**Issue by mindryder** [LordDeatHunter/FabricWaystones#221] opened 2023-09-19 03:32 UTC
### Description

Pls make option for teleport with mount (mob) if already sit on mount

### Describe the solution you would like

Pls make option for teleport with mount (mob) if already sit on mount

**Comment by LordDeatHunter** [comment] 2023-10-08 18:57
Duplicate of #168

**Closed by LordDeatHunter** 2023-10-08 18:57 UTC
