### ISSUE TITLE
[Bug] Sometimes using a waystone destroys an off-hand item

### ISSUE THREAD

**Issue by Tomatobird8** [LordDeatHunter/FabricWaystones#41] opened 2021-06-21 16:06 UTC
Video: https://streamable.com/s6slkn
Destorys shields and bows for example,

**Comment by Rayxanber** [comment] 2021-07-07 10:55
Have noticed this as well. Happening to multiple people on our server. Mod Version 2.0.1, Minecraft Version 1.17

**Comment by Fourmisain** [comment] 2021-07-07 21:33
This is most likely caused by this piece of code, note that in the example video, the main hand was actually empty:
https://github.com/LordDeatHunter/FabricWaystones/blob/4b882b5d4b207ef874d819ee82dc63f0c7ccdcd8/src/main/java/wraith/waystones/block/WaystoneBlockEntity.java#L341-L343
`playerEntity.getActiveHand()` can return `Hand.OFF_HAND` when the `OFF_HAND_ACTIVE_FLAG` flag of `LIVING_FLAGS` is set.

I think using an offhand item like a shield will set this flag and since you right click to use the item but also to open the GUI, the flag probably gets set when opening the GUI and is only reset once it's closed again or something like that.

The bug should be fixed by either replacing `playerEntity.getActiveHand()` with `Hand.MAIN_HAND` or replacing `getMainHandStack()` with... `getActiveItem()` or `getStackInHand(getActiveHand())`?

The real question is though: What is this piece of code is even for?

Meanwhile, as a workaround: Hold an item in your main hand!

**Closed** 2021-07-08 22:12 UTC

**Comment by endavis** [comment] 2021-07-09 16:17
Will this be backported to 1.16.5?
